export {default as Login} from "./auth/Login";
export {default as SignUp} from "./auth/SignUp"
export {default as PasswordReset} from "./auth/PasswordReset"
export {default as Home} from "./frontOffice/Home"
export {default as NotFound} from "./frontOffice/NotFound"
export {default as Education} from "./frontOffice/Education"
export {default as DenonciationProcess} from "./frontOffice/DenonciationProcess"
export {default as Denonciation} from "./frontOffice/Denonciation"
export {default as Notification} from "./frontOffice/Notification"